import { Geist, Geist_Mono } from "next/font/google";
import AbstractWalletProvider from "@/components/abstract/abstractWalletProvider.js";
import "./globals.css";
import ClientProvider from "@/redux/clientProvider";
import { WebSocketProvider } from "./WebSocketProvider";
import { CampaignProvider } from "./CampaignProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "UGC Fun",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClientProvider>
      <AbstractWalletProvider>
        <html lang="en">
          <body className={`${geistSans.variable} ${geistMono.variable}`}>
            <WebSocketProvider>
              <CampaignProvider>
                {children}
              </CampaignProvider>
            </WebSocketProvider>
          </body>
        </html>
      </AbstractWalletProvider>
    </ClientProvider>
  );
}
